[project]
name = "afixl"
version = "0.1.0"
description = "A conversational LLM agent for automated program repair guided by fuzzing"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "docker>=7.1.0",
    "pydantic>=2.11.7",
    "pydantic-ai>=0.3.4",
    "sqlite-vec>=0.1.6",
]
